name: Build and test

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - name: GCC
            cc: gcc
            cxx: g++
          - name: Clang
            cc: clang
            cxx: clang++

    name: ${{ matrix.compiler.name }}
    env:
      CC: ${{ matrix.compiler.cc }}
      CXX: ${{ matrix.compiler.cxx }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Configure
        run: cmake --preset debug

      - name: Build
        run: cmake --build --preset debug --parallel

      - name: Test
        run: ctest --preset debug
